CREATE TABLE BacASableRapportProdAsten(
	[Domaine] [varchar](100),
	[Serveur] [varchar](100),
	[Tache] [varchar](100),
	[MU] [varchar](100),
	[Unité de gestion] [varchar](100),
	[sess] [varchar](100),
	[Session] [varchar](100),
	[Job] [varchar](100),
	[Uproc] [varchar](100),
	[Statut] [varchar](100),
	[Prévu] [datetime],
	[Début] [datetime],
	[Fin] [datetime],
	[Durée] [datetime],
	[Temps estimé] [datetime],
	[Fil rouge] [numeric](15, 5),
	[Info] [varchar](100),
	[Date création fichier] [datetime],
	[Date dernière modification] [datetime],
	[ID jour] [numeric](15, 5),
	[Flag Fichier] [numeric](8, 0),
	[Nom du fichier] [varchar](100),
	[ID] [numeric](15, 5),
	[Nombre de lignes] [numeric](15, 5),
	[Taille du fichier] [numeric](15, 5),
	[Auteur du fichier] [varchar](100),
	[ID fichier] [numeric](15, 5))